Fix `fetch_openml` parser warning
skrub-data/skrub pull request #518
Opened 2023-03-02 14:14 UTC by LilianBoulard

Fixes #517

2023-03-03 09:06 UTC, GaelVaroquaux commented
The proposed fix cannot work on older versions of scikit-learn (and the test are failing).

The correct fix is to test for the version of scikit-learn and add the argument only if the version of scikit-learn is recent enough.

2023-03-03 10:17 UTC, LilianBoulard commented
I know but even with the most recent version, the tests fail, and I'm trying to understand why.
I agree the fix I submitted was lazy, I'll look into the error :)

2023-03-03 10:32 UTC, GaelVaroquaux commented
> I agree the fix I submitted was lazy, I'll look into the error :)

Lazy is good when it works :)

2023-03-03 13:32 UTC, LilianBoulard commented
So the issue we have is related to scikit-learn/scikit-learn#25478.
The PR scikit-learn/scikit-learn#25511 has been submitted and should be ready for sklearn 1.2.2. I can preemptively submit a fix, but we should leave this PR open until it's released.

2023-03-13 12:32 UTC, GaelVaroquaux commented
Tests are passing. Is this mergeable? I noted that the PR is still in draft mode.

2023-03-13 12:35 UTC, GaelVaroquaux requested changes
One small suggestion

2023-03-13 12:35 UTC, GaelVaroquaux commented on dirty_cat/datasets/_fetching.py
> -    )
Cosmetic: to minimize code duplicate, I would rather use a kwarg dictionary: initialize it empty, populate it with the right key, value pairs in "if/then" clause, and call "fetch_openml" expending this dict with "**kwargs".

2023-03-14 09:32 UTC, GaelVaroquaux approved these changes
LGTM, thanks a lot!

2023-03-14 09:34 UTC, GaelVaroquaux commented
The code looks just right!

We have test failing on the main branch (not sure how we got there, we screwed up at some point). Out of good practice, I'll wait for these to be fixed, and rebase, so as to merge with passing tests.

2023-03-31 07:40 UTC, jovan-stojanovic approved these changes
Merging now the tests have passed.

2023-03-31 07:41 UTC, merged