DOC Rework main encoding example
skrub-data/skrub pull request #684
Opened 2023-07-31 13:54 UTC by LilianBoulard

Extracted from #546.

Fixes #341
Motivated by #662 (fixes #662)

2023-08-02 17:16 UTC, GaelVaroquaux commented on examples/01_dirty_categories.py
>  """
We should change the file name

2023-08-02 19:58 UTC, GaelVaroquaux requested changes
A few suggestions of reformulation, and a couple of things to adress.

2023-08-02 19:58 UTC, GaelVaroquaux commented on examples/01_dirty_categories.py
> +# Let's extract a sample to have a more focused view: we'll limit our
I would like that we first run the analysis (pipelining TableVectorizer with HBGT before discussing this

2023-08-02 19:58 UTC, GaelVaroquaux commented on examples/01_dirty_categories.py
> +# Let's extract a sample to have a more focused view: we'll limit our
Put it at the bottom, where we discuss the GapEncoder.

2023-08-02 19:58 UTC, GaelVaroquaux commented on examples/01_dirty_categories.py
> +# TODO
It seems to me that there is still a bit of work.

At least, we should put back the discussion on the feature names from the original example.

2023-08-02 19:58 UTC, GaelVaroquaux commented on examples/01_dirty_categories.py
> +# `employee_position_title` and `division`, and a |DatetimeEncoder| to the
It seems that the replacement of the DatetimeEncoder did not work:
![image](https://github.com/skrub-data/skrub/assets/208217/a9948740-9748-42fe-9c41-a3c5dcf1081a)

2023-09-13 14:13 UTC, Vincent-Maladiere reviewed
Great concision effort, @LilianBoulard and @jovan-stojanovic (-200 lines!). This is way more user-friendly and straight to the point :)
Here is a review to extend this effort.

2023-09-13 14:13 UTC, Vincent-Maladiere commented on examples/01_encodings.py
> +plt.show()
Nitpick, improves readability
```suggestion
top_indices = indices[:20]
labels = np.array(feature_names)[top_indices]

plt.figure(figsize=(12, 9))
plt.barh(
    y=labels,
    x=avg_importances[top_indices],
    yerr=std_importances[top_indices],
    color="b",
)
plt.yticks(fontsize=15)
plt.title("Feature importances")
plt.tight_layout(pad=1)
plt.show()
```

2023-09-13 14:13 UTC, Vincent-Maladiere commented on examples/01_encodings.py
> +std = np.std([tree.feature_importances_ for tree in regressor.estimators_], axis=0)
Nitpick: improve readability
```suggestion
avg_importances = regressor.feature_importances_
std_importances = np.std([tree.feature_importances_ for tree in regressor.estimators_], axis=0)
```

2023-09-14 07:56 UTC, jovan-stojanovic commented on examples/01_encodings.py
> +#   - dirty categorical ('employee_position_title', 'division').
I followed what was recommended in #692, we might have a discussion later there to see what's best. Is that ok?

2023-09-14 11:07 UTC, Vincent-Maladiere commented on examples/01_encodings.py
> +#   - dirty categorical ('employee_position_title', 'division').
#692 suggests using e.g. ``'gender'``, written \``'gender'`` for datasets and column names, right?

2023-09-14 11:44 UTC, jovan-stojanovic commented on examples/01_encodings.py
> +#   - dirty categorical ('employee_position_title', 'division').
Ah ok, yes that seems to work. Will apply.

2023-09-25 15:35 UTC, Vincent-Maladiere reviewed
Last round of nitpick, and then we're good to go :)

2023-09-25 15:35 UTC, Vincent-Maladiere commented on examples/01_encodings.py
> +#       'gender', 'department', 'department_name' and 'assignment_category'.
```suggestion
#       ``'gender'``, ``'department'``, ``'department_name'`` and ``'assignment_category'``.
```

2023-09-25 15:35 UTC, Vincent-Maladiere commented on examples/01_encodings.py
> +#       and 'division'. The |GapEncoder| is a powerful encoder that can handle dirty
```suggestion
#     - The |GapEncoder| for high cardinality string columns, ``'employee_position_title'``
#       and ``'division'``. The |GapEncoder| is a powerful encoder that can handle dirty
```

2023-09-25 15:50 UTC, Vincent-Maladiere approved these changes
Thanks @jovan-stojanovic, LGTM! I think we can merge it as it is.

2023-09-26 08:53 UTC, merged