Rework `GapEncoder` example
skrub-data/skrub pull request #686
Opened 2023-07-31 14:07 UTC by LilianBoulard

Extracted from #546.

2023-08-03 09:48 UTC, jovan-stojanovic requested changes
Thanks @LilianBoulard, this looks very good! A few comments.

2023-08-03 09:48 UTC, jovan-stojanovic commented on examples/02_investigating_dirty_categories.py
> +# which we will demonstrate now.
```suggestion
# The |GapEncoder| is more scalable and interpretable than the |SimilarityEncoder|,
# which we will demonstrate now.
```

2023-08-03 09:48 UTC, jovan-stojanovic commented on examples/02_investigating_dirty_categories.py
> +# First, let's retrieve the dataset:
```suggestion
# First, let's retrieve the `employee salaries dataset <https://www.openml.org/d/42125>`_:
```

2023-08-03 09:48 UTC, jovan-stojanovic commented on examples/02_investigating_dirty_categories.py
> +# And carry out some basic preprocessing
```suggestion
# And carry out some basic preprocessing:
```

2023-08-03 09:48 UTC, jovan-stojanovic commented on examples/02_investigating_dirty_categories.py
> +# Let's also get the dirty column we want to encode
```suggestion
# Let's look at the job titles, the dirty column we want to encode:
```

2023-08-03 09:48 UTC, jovan-stojanovic commented on examples/02_investigating_dirty_categories.py
> +# Then, we'll create an instance of the |GapEncoder| with 10 components:
```suggestion
# Then, we'll create an instance of the |GapEncoder| with 10 components. This means that the encoder will attempt to extract 10 latent topics from the input data:
```

2023-08-03 09:48 UTC, jovan-stojanovic commented on examples/02_investigating_dirty_categories.py
>  # This enables us to understand the encoding of different samples
```suggestion
# This enables us to understand the encoding of different samples.
```

2023-08-03 20:28 UTC, GaelVaroquaux reviewed
LGTM, but I think that we also need to change the index because there is a link to the example which has been renamed, no?

2023-08-03 20:28 UTC, GaelVaroquaux commented on examples/02_feature_interpretation_with_gapencoder.py
> +|GapEncoder|, one of the encoders provided by skrub.
```suggestion
|GapEncoder|, one of the categorical encoders provided by skrub.
```

2023-08-03 20:28 UTC, GaelVaroquaux commented on examples/02_feature_interpretation_with_gapencoder.py
> +# |SimilarityEncoder|, which we will demonstrate now.
Let's not position the GapEncoder with regards to the SimilarityEncoder, as we are no longer putting emphasis on the latter
```suggestion
# The |GapEncoder| is scalable and interpretable in terms of
# finding latent categories, as we will show.
```

2023-08-03 20:28 UTC, GaelVaroquaux commented on examples/02_feature_interpretation_with_gapencoder.py
> +# Then, we'll create an instance of the |GapEncoder| with 10 components.
```suggestion
# Then, we create an instance of the |GapEncoder| with 10 components.
```

2023-08-03 20:28 UTC, GaelVaroquaux commented on examples/02_feature_interpretation_with_gapencoder.py
> +# Finally, we'll fit the model on the dirty categorical data and transform it
```suggestion
# Finally, we fit the model on the dirty categorical data and transform it
```

2023-08-18 08:23 UTC, jovan-stojanovic commented
You should adapt the example to the fact that #581 was merged

2023-09-11 13:29 UTC, jovan-stojanovic commented
Thanks @LilianBoulard! I will take over this PR so we move faster.

2023-09-25 15:47 UTC, Vincent-Maladiere reviewed
Great concision effort again (-100!). My main remark regards using "dirty" either for variable names or explainers. This can be easily misinterpreted, and I'd rather have "high cardinality" instead or "noisy" if you prefer. WDYT?

2023-09-25 15:47 UTC, Vincent-Maladiere commented on examples/02_feature_interpretation_with_gapencoder.py
> +    print(f"Topic n°{k}: {labels}")
This part (and the subsequent visualization) is great! A real wow effect 👍

2023-09-29 13:24 UTC, jovan-stojanovic commented
> My main remark regards using "dirty" for variable names and explainers. This can be easily misinterpreted, and I'd rather have "high cardinality, "high entropy" or "noisy" instead. WDYT?

You have a point, looking back at the example I realize that we introduce "dirty" without explaining what it means. I will correct this.

This term "dirty" is something that [was used in the literature](https://inria.hal.science/hal-01806175) and in dirty-cat to describe data whose source of variation can be anything, meaningful and meaningful as opposed to "noisy" for instance, which has different connotation (often synonym to meaningless) in some fields (e.g. econometrics, signal processing).

As for alternatives, I like "high cardinality" ([also used in literature](https://inria.hal.science/hal-02171256v4)), "high entropy" may be less known among our users.

2023-09-29 13:42 UTC, jovan-stojanovic commented
WDYT of this version? @Vincent-Maladiere

2023-09-29 13:51 UTC, Vincent-Maladiere commented
> This term "dirty" is something that [was used in the literature](https://inria.hal.science/hal-01806175) and in dirty-cat to describe data whose source of variation can be anything

Yes, we used it in a paper, but it doesn't mean it conveys the right message 😅. External users might be surprised by this wording, like Cailean Osborne —he was in high spirits when he found out we call those "dirty"!

> WDYT of this version? @Vincent-Maladiere

Well, I still prefer using "high cardinality" if you like. Let's bring this up during the next meeting.

2023-11-21 16:38 UTC, Vincent-Maladiere approved these changes
LGTM!

2023-11-21 16:38 UTC, merged