Add `SimilarityEncoder` explanation example
skrub-data/skrub pull request #688
Opened 2023-07-31 14:16 UTC by LilianBoulard

Extracted from #546.

2023-08-03 09:27 UTC, jovan-stojanovic commented on examples/02_explaining_similarity_encoding.py
> +sorted_values = values["employee_position_title"].sort_values().unique()
Do a small print of `sorted_values` so the user does not need to scroll up to see what is the column we are working on

2023-08-03 09:37 UTC, jovan-stojanovic requested changes
Very nice! A few small comments.

2023-08-03 09:37 UTC, jovan-stojanovic commented on examples/02_explaining_similarity_encoding.py
> +sorted_values = values["employee_position_title"].sort_values().unique()
Do a small print of `sorted_values` here so the user does not need to scroll up to see what is the column we are working on.

2023-08-03 09:37 UTC, jovan-stojanovic commented on examples/02_explaining_similarity_encoding.py
> +transformed_values = similarity_encoder.fit_transform(sorted_values.reshape(-1, 1))
Print a small subset of the similarity matrix to show what it looks like?
You can quickly state below that the values are in between 0 and 1, based on the level of n-gram similarity.

2023-08-03 09:37 UTC, jovan-stojanovic commented on examples/02_explaining_similarity_encoding.py
> +print(sorted_values.shape)
If you insert the above explanations, I feel you don't need this, and you can directly do the plot with the points.

2023-08-03 09:37 UTC, jovan-stojanovic commented on examples/02_explaining_similarity_encoding.py
> +# very close to "Senior Supply Technician": therefore, we grasp the
```suggestion
# very close to "Senior Supply Technician": therefore, the |SimilarityEncoder| grasps the
```

2023-08-03 09:37 UTC, jovan-stojanovic commented on examples/02_explaining_similarity_encoding.py
> +# as well as the "Technician" part of this category.
```suggestion
# as well as the "Technician" part of this category.
#
# In conclusion, the |SimilarityEncoder| works as a generalized upgrade of the |OneHotEncoder|, that takes into account string similarities.
```

Propose a final conclusion (feel free to improve it).

2023-08-03 17:45 UTC, GaelVaroquaux reviewed
I think that this example should be merged in the one comparing categorical encoders in https://github.com/skrub-data/skrub/pull/685

2023-09-12 14:27 UTC, jovan-stojanovic commented
This will merged with #685 for simplicity.

2023-09-12 14:27 UTC, closed without merging