MAIN Improve the error message for Pandas sparse arrays in TableVectorizer
skrub-data/skrub pull request #737
Opened 2023-09-08 13:12 UTC by Vincent-Maladiere

**References**
Addresses https://github.com/skrub-data/skrub/issues/679

**What does this PR implement?** 
`TableVectorizer` currently doesn't support sparse matrices. Until then, we should also prevent users from using Pandas sparse arrays.

This PR suggests that, during the `_check_input` call, we iterate on dataframe columns to look for the "sparse" accessor. We raise an error when at least one column is sparse.

**Alternative solution**
AFAIK, there is no way to identify a sparse column within a Pandas dataframe without iterating on the columns.

cc @LeoGrin

2023-09-22 13:45 UTC, LeoGrin requested changes
Thanks!
> AFAIK, there is no way to identify a sparse column within a Pandas dataframe without iterating on the columns.

I don't see any either.

2023-09-22 13:45 UTC, LeoGrin commented on skrub/_table_vectorizer.py
>          if not isinstance(X, pd.DataFrame):
I think moving your code after the conversion to pandas would fix the errors you have.

2023-09-25 09:33 UTC, LeoGrin approved these changes

2023-09-25 09:55 UTC, jovan-stojanovic approved these changes

2023-09-25 09:55 UTC, merged