DatetimeEncoder fixes
skrub-data/skrub pull request #743
Opened 2023-09-20 13:14 UTC by LeoGrin

- Fix #741 Remove millisecond extraction in DatetimeEncoder (Turns out you pandas' `DatetimeIndex` don't have a `millisecond` attribute.)
- Fix #745 Stop using the `floor` function and simplify the logic to check if we need `total_time`
- Close #744 Adds a `None` option for `extract_until` to only extract `total_time`.

@jeromedockes

2023-09-22 08:42 UTC, Vincent-Maladiere approved these changes
Thanks @LeoGrin for this bug fix. This might help fix https://github.com/skrub-data/skrub/issues/741 afterward.
Overall, I'm concerned with the quality of this estimator as we have other bugs like https://github.com/skrub-data/skrub/issues/746. This means that we didn't test it enough.

2023-09-22 13:37 UTC, Vincent-Maladiere commented
Hey @LeoGrin, I'd advocate not to change the scope of PRs once started because it's confusing to review. To fix new issues, let's open new PRs instead :)

2023-09-26 13:22 UTC, jeromedockes commented on skrub/_datetime_encoder.py
> +        if self.extract_until not in TIME_LEVELS and not self.extract_until is None:
it's an unimportant style detail but most people would prefer `x is not None` to `not x is None`

2023-09-28 10:22 UTC, Vincent-Maladiere reviewed
I think returning the total number of seconds since Epoch when `self.extract_until=None` is misleading for the user.
I'd rather have `self.extract_until=None` as a no-op (not returning anything), and have an additional keyword init parameter like `self.seconds_since_epoch`.
What do you both think?

Otherwise, I haven't specific remarks on the PR itself, but I plan to refactorize a lot of the DatetimeEncoder implementation that I'm not super happy with in a subsequence PR.

2023-09-28 10:48 UTC, jeromedockes commented
> I think returning the total number of seconds since Epoch when `self.extract_until=None` is misleading for the user.
> I'd rather have `self.extract_until=None` as a no-op (not returning anything), and have an additional keyword init parameter like `self.seconds_since_epoch`.
> What do you both think?
>

I agree, that seems better. If we don't want to add a parameter we could
even always return the seconds since epoch in addition to any other
features the user requests

> Otherwise, I haven't specific remarks on the PR itself, but I plan to refactorize a lot of the DatetimeEncoder implementation that I'm not super happy with in a subsequence PR.
>

I agree the DateTimeEncoder could use some cleanup. For example it re-parses the whole date column to extract each feature.

Also the DateTimeEncoder and the TableVectorizer both parse date strings, and they do it in different ways so it may be worth thinking about their respective responsibilities and doing some refactoring.

2023-09-28 13:02 UTC, jeromedockes commented
> Thinking about it a bit more, it would better for the shape of the output to not depend on the data, for instance if we want to use this inside a grid search, so it may be better to get rid of the logic we have now (check if columns are constant).

I think that's a good idea. Dropping constant columns can be done later
in the pipeline with a VarianceThreshold transformer from scikit-learn.

I guess the idea was to avoid adding eg an hour column full of 0 when
the column we are transforming contains dates not times. But for that it
may be better to rely on the date format detected when parsing the dates
than to check the variance a posteriori

2023-09-29 14:04 UTC, Vincent-Maladiere commented
> I guess the idea was to avoid adding eg an hour column full of 0 when
the column we are transforming contains dates not times. But for that it
may be better to rely on the date format detected when parsing the dates
than to check the variance a posterior

Alternatively, we could let the user switch between these two behaviors with an additional `drop_if_constant` keyword argument.

> I think that's a good idea. Dropping constant columns can be done later
in the pipeline with a VarianceThreshold transformer from scikit-learn.

We definitely need to add the `VarianceThreshold` estimator to the example!

2023-09-29 15:00 UTC, Vincent-Maladiere requested changes
Let's change the behavior of `extract_until=None` to be a no-op and add an extra `add_total_seconds_since_epoch` or `add_seconds_since_epoch` keyword parameter (default True) as discussed :)

2023-09-29 15:00 UTC, Vincent-Maladiere commented on CHANGES.rst
> +* Fix bugs which was triggered when `extract_until` was "year", "month", "microseconds"
```suggestion
* Fix bugs which where triggered when `extract_until` was "year", "month", "microseconds"
```

2023-10-02 13:39 UTC, Vincent-Maladiere approved these changes
Let's merge so that we can do the refactoring soon.

2023-10-02 13:39 UTC, merged